controller_list:
 - name: hdt_arm/arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - drive1_joint
     - drive2_joint
     - drive3_joint
     - drive4_joint
     - drive5_joint
     - drive6_joint
